### ISSUE TITLE
Provide sneak peak in final data.

### ISSUE THREAD

**Issue by prabhushrikant** [ShelterApp/AddResources#4]
After the data is scrapped and finalized , provide following statistics about the data

- Entries per category.
- Entries per city 
- Categories per city.

This will allow us to determine how much coverage we have, which cities we are good to launch etc

**Comment by prabhushrikant** [comment]
Azure App Insights can create such reports.

**Comment by ShelterApp** [comment]
If it's purely database queries , we have look some dashboarding charts option on mongodb itself. 

![image](https://user-images.githubusercontent.com/61941223/103747339-56df0d00-4fb7-11eb-87f1-0c479e317273.png)
